spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_exchange_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

app:
  image-url: http://localhost:8080/api/v1/images/